export interface SecaoAlbum {
  nome: string;
  prefixo: string;
  total: number;
}

export const SECOES_ALBUM: SecaoAlbum[] = [
  { nome: 'Fifa World Cup', prefixo: 'FWC', total: 20 },
  { nome: 'México', prefixo: 'MEX', total: 20 },
  { nome: 'África do Sul', prefixo: 'RSA', total: 20 },
  { nome: 'Coreia do Sul', prefixo: 'KOR', total: 20 },
  { nome: 'República Tcheca', prefixo: 'CZE', total: 20 },
  { nome: 'Canadá', prefixo: 'CAN', total: 20 },
  { nome: 'Bósnia', prefixo: 'BIH', total: 20 },
  { nome: 'Catar', prefixo: 'QAT', total: 20 },
  { nome: 'Suíça', prefixo: 'SUI', total: 20 },
  { nome: 'Brasil', prefixo: 'BRA', total: 20 },
  { nome: 'Marrocos', prefixo: 'MAR', total: 20 },
  { nome: 'Haiti', prefixo: 'HAI', total: 20 },
  { nome: 'Escócia', prefixo: 'SCO', total: 20 },
  { nome: 'Estados Unidos', prefixo: 'USA', total: 20 },
  { nome: 'Paraguai', prefixo: 'PAR', total: 20 },
  { nome: 'Austrália', prefixo: 'AUS', total: 20 },
  { nome: 'Turquia', prefixo: 'TUR', total: 20 },
  { nome: 'Alemanha', prefixo: 'GER', total: 20 },
  { nome: 'Curaçao', prefixo: 'CUW', total: 20 },
  { nome: 'Costa do Marfim', prefixo: 'CIV', total: 20 },
  { nome: 'Equador', prefixo: 'ECU', total: 20 },
  { nome: 'Países Baixos', prefixo: 'NED', total: 20 },
  { nome: 'Japão', prefixo: 'JPN', total: 20 },
  { nome: 'Suécia', prefixo: 'SWE', total: 20 },
  { nome: 'Tunísia', prefixo: 'TUN', total: 20 },
  { nome: 'Bélgica', prefixo: 'BEL', total: 20 },
  { nome: 'Egito', prefixo: 'EGY', total: 20 },
  { nome: 'Irã', prefixo: 'IRN', total: 20 },
  { nome: 'Nova Zelândia', prefixo: 'NZL', total: 20 },
  { nome: 'Espanha', prefixo: 'ESP', total: 20 },
  { nome: 'Cabo Verde', prefixo: 'CPV', total: 20 },
  { nome: 'Arábia Saudita', prefixo: 'KSA', total: 20 },
  { nome: 'Uruguai', prefixo: 'URU', total: 20 },
  { nome: 'França', prefixo: 'FRA', total: 20 },
  { nome: 'Senegal', prefixo: 'SEN', total: 20 },
  { nome: 'Iraque', prefixo: 'IRQ', total: 20 },
  { nome: 'Noruega', prefixo: 'NOR', total: 20 },
  { nome: 'Argentina', prefixo: 'ARG', total: 20 },
  { nome: 'Argélia', prefixo: 'ALG', total: 20 },
  { nome: 'Áustria', prefixo: 'AUT', total: 20 },
  { nome: 'Jordânia', prefixo: 'JOR', total: 20 },
  { nome: 'Portugal', prefixo: 'POR', total: 20 },
  { nome: 'RD do Congo', prefixo: 'COD', total: 20 },
  { nome: 'Uzbequistão', prefixo: 'UZB', total: 20 },
  { nome: 'Colômbia', prefixo: 'COL', total: 20 },
  { nome: 'Inglaterra', prefixo: 'ENG', total: 20 },
  { nome: 'Croácia', prefixo: 'CRO', total: 20 },
  { nome: 'Gana', prefixo: 'GHA', total: 20 },
  { nome: 'Panamá', prefixo: 'PAN', total: 20 },
  { nome: 'Coca-Cola', prefixo: 'CC', total: 14 },
];

export const COUNTRY_FLAGS: Record<string, string> = {
  FWC: '🏆',
  MEX: '🇲🇽', RSA: '🇿🇦', KOR: '🇰🇷', CZE: '🇨🇿',
  CAN: '🇨🇦', BIH: '🇧🇦', QAT: '🇶🇦', SUI: '🇨🇭',
  BRA: '🇧🇷', MAR: '🇲🇦', HAI: '🇭🇹', SCO: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  USA: '🇺🇸', PAR: '🇵🇾', AUS: '🇦🇺', TUR: '🇹🇷',
  GER: '🇩🇪', CUW: '🇨🇼', CIV: '🇨🇮', ECU: '🇪🇨',
  NED: '🇳🇱', JPN: '🇯🇵', SWE: '🇸🇪', TUN: '🇹🇳',
  BEL: '🇧🇪', EGY: '🇪🇬', IRN: '🇮🇷', NZL: '🇳🇿',
  ESP: '🇪🇸', CPV: '🇨🇻', KSA: '🇸🇦', URU: '🇺🇾',
  FRA: '🇫🇷', SEN: '🇸🇳', IRQ: '🇮🇶', NOR: '🇳🇴',
  ARG: '🇦🇷', ALG: '🇩🇿', AUT: '🇦🇹', JOR: '🇯🇴',
  POR: '🇵🇹', COD: '🇨🇩', UZB: '🇺🇿', COL: '🇨🇴',
  ENG: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', CRO: '🇭🇷', GHA: '🇬🇭', PAN: '🇵🇦',
  CC: '🥤'
};